---
- name: Define BMOPATH
  set_fact:
    BMOPATH: "{{ GOPATH }}/src/github.com/metal3-io/baremetal-operator"

- name: "Generate templates for v1alpha3"
  include: generate_templates.yml


- name: Provision cluster
  k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_cluster_centos.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action == "provision_cluster"

- name: Create control plane
  k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_controlplane_centos.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action == "provision_controlplane"

- name: Create worker nodes
  k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_workers_centos.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action == "provision_workers"

- name: Deprovision worker nodes
  k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_workers_centos.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action == "deprovision_workers"

- name: Deprovision control plane
  k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_controlplane_centos.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action == "deprovision_controlplane"

- name: Deprovision cluster
  k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_cluster_centos.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action == "deprovision_cluster"

- name: Cleanup deployment
  include: cleanup.yml
  when: v1aX_integration_test_action == "cleanup"

- name: Node remediation
  include: remediation.yml
  when: v1aX_integration_test_action == "remediation"
